#!/usr/bin/env python3
"""Sample per-character colours from the sliced sprites into src/palettes.js."""
import os
import json

from PIL import Image
import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SPR = os.path.join(ROOT, "assets", "sprites")
OUT = os.path.join(ROOT, "src", "palettes.js")


def hexs(c):
    return "#%02x%02x%02x" % c if c else "#8888aa"


def median(pix):
    if len(pix) == 0:
        return None
    return tuple(int(v) for v in np.median(pix, axis=0))


def skin_like(p):
    r, g, b = p[:, 0], p[:, 1], p[:, 2]
    return (r > 120) & (g > 70) & (b > 50) & (r >= g) & (g >= b) & ((r - b) > 15) & ((r - b) < 140)


def sample(path):
    a = np.asarray(Image.open(path).convert("RGBA")).astype(int)
    al = a[:, :, 3]
    ys, xs = np.where(al > 140)
    if len(ys) < 30:
        return None
    y0, y1 = ys.min(), ys.max()

    def band(f0, f1, filt=None):
        yy0, yy1 = int(y0 + (y1 - y0) * f0), int(y0 + (y1 - y0) * f1)
        reg = a[yy0:yy1]
        px = reg[reg[:, :, 3] > 140][:, :3]
        if filt is not None and len(px):
            px = px[filt(px)]
        return median(px)

    hair = band(0.0, 0.20, lambda p: ~skin_like(p))
    skin = band(0.16, 0.34, skin_like) or band(0.16, 0.34)
    top = band(0.42, 0.62)
    bottom = band(0.66, 0.92)
    px = a[al > 140][:, :3]
    sat = px.max(1) - px.min(1)
    accent = tuple(int(v) for v in px[int(np.argmax(sat))]) if len(px) else top
    return {"hair": hexs(hair), "skin": hexs(skin), "top": hexs(top),
            "bottom": hexs(bottom), "accent": hexs(accent)}


def main():
    pal = {}
    for fn in sorted(os.listdir(SPR)):
        if fn.endswith(".png"):
            r = sample(os.path.join(SPR, fn))
            if r:
                pal[fn[:-4]] = r
    with open(OUT, "w") as f:
        f.write("// AUTO-GENERATED by tools/extract_palettes.py — do not edit by hand.\n")
        f.write("export const PALETTES = ")
        f.write(json.dumps(pal, indent=2))
        f.write(";\n\nexport function getPalette(id) {\n  return PALETTES[id];\n}\n")
    print("wrote", len(pal), "palettes ->", OUT)


if __name__ == "__main__":
    main()
