// AUTO-GENERATED by tools/extract_palettes.py — do not edit by hand.
export const PALETTES = {
  "ENFJ_F": {
    "hair": "#505347",
    "skin": "#f4d09c",
    "top": "#676f46",
    "bottom": "#6a8052",
    "accent": "#cca42c"
  },
  "ENFJ_M": {
    "hair": "#4d5246",
    "skin": "#f2ca91",
    "top": "#657446",
    "bottom": "#5c6f51",
    "accent": "#eeb731"
  },
  "ENFP_F": {
    "hair": "#5f7e67",
    "skin": "#bd9b69",
    "top": "#646c4d",
    "bottom": "#546f5a",
    "accent": "#fab52b"
  },
  "ENFP_M": {
    "hair": "#6d7c58",
    "skin": "#f0cc95",
    "top": "#818752",
    "bottom": "#56755e",
    "accent": "#e0915b"
  },
  "ENTJ_F": {
    "hair": "#6c5b5f",
    "skin": "#f6d9b2",
    "top": "#78615f",
    "bottom": "#795f60",
    "accent": "#e8b873"
  },
  "ENTJ_M": {
    "hair": "#7d6472",
    "skin": "#f4d4a9",
    "top": "#7d6573",
    "bottom": "#5a5463",
    "accent": "#f0ba7e"
  },
  "ENTP_F": {
    "hair": "#605e54",
    "skin": "#f6d6ab",
    "top": "#887184",
    "bottom": "#5c5662",
    "accent": "#e7ad5c"
  },
  "ENTP_M": {
    "hair": "#797877",
    "skin": "#f7d5a7",
    "top": "#686569",
    "bottom": "#62554d",
    "accent": "#e79b63"
  },
  "ESFJ_F": {
    "hair": "#5f625f",
    "skin": "#f5d6ad",
    "top": "#548a87",
    "bottom": "#578d90",
    "accent": "#ce9a4d"
  },
  "ESFJ_M": {
    "hair": "#5d757f",
    "skin": "#f0cb96",
    "top": "#8f9e96",
    "bottom": "#759791",
    "accent": "#f0b43b"
  },
  "ESFP_F": {
    "hair": "#685f4c",
    "skin": "#e5cb9b",
    "top": "#c2995a",
    "bottom": "#dcb051",
    "accent": "#edb52c"
  },
  "ESFP_M": {
    "hair": "#66635b",
    "skin": "#f4d19f",
    "top": "#ca9b43",
    "bottom": "#ba9038",
    "accent": "#e7ae21"
  },
  "ESTJ_F": {
    "hair": "#545e5f",
    "skin": "#efd1a7",
    "top": "#53717a",
    "bottom": "#3e6471",
    "accent": "#facc83"
  },
  "ESTJ_M": {
    "hair": "#5c6360",
    "skin": "#f4d1a3",
    "top": "#82a79e",
    "bottom": "#507f79",
    "accent": "#e1a865"
  },
  "ESTP_F": {
    "hair": "#e4b13b",
    "skin": "#e8c690",
    "top": "#c2973a",
    "bottom": "#d6a636",
    "accent": "#eeb814"
  },
  "ESTP_M": {
    "hair": "#86632b",
    "skin": "#f2ca8c",
    "top": "#d3a33a",
    "bottom": "#9f7e39",
    "accent": "#f8c824"
  },
  "INFJ_F": {
    "hair": "#607861",
    "skin": "#f4d6ad",
    "top": "#526b56",
    "bottom": "#5f735a",
    "accent": "#d19e3f"
  },
  "INFJ_M": {
    "hair": "#6e6050",
    "skin": "#e8cca2",
    "top": "#8a895c",
    "bottom": "#707b56",
    "accent": "#d99049"
  },
  "INFP_F": {
    "hair": "#7a8b57",
    "skin": "#d8c389",
    "top": "#98a063",
    "bottom": "#768d6c",
    "accent": "#f6d146"
  },
  "INFP_M": {
    "hair": "#52524a",
    "skin": "#f4cd97",
    "top": "#828340",
    "bottom": "#848042",
    "accent": "#e9a82a"
  },
  "INTJ_F": {
    "hair": "#846e84",
    "skin": "#f6d9b1",
    "top": "#b096a1",
    "bottom": "#b7a5a0",
    "accent": "#efbb7f"
  },
  "INTJ_M": {
    "hair": "#826a81",
    "skin": "#f7d8b0",
    "top": "#a46e70",
    "bottom": "#6d5562",
    "accent": "#f0b076"
  },
  "INTP_F": {
    "hair": "#8c6b70",
    "skin": "#d3c2a7",
    "top": "#b4a08c",
    "bottom": "#c8beaf",
    "accent": "#f2ab56"
  },
  "INTP_M": {
    "hair": "#595a5d",
    "skin": "#f4d2a5",
    "top": "#9f767b",
    "bottom": "#6b5e6d",
    "accent": "#d6915c"
  },
  "ISFJ_F": {
    "hair": "#638f88",
    "skin": "#f1d0a4",
    "top": "#7f9489",
    "bottom": "#578c88",
    "accent": "#e8ab6c"
  },
  "ISFJ_M": {
    "hair": "#537b78",
    "skin": "#f1c997",
    "top": "#9ba090",
    "bottom": "#508179",
    "accent": "#f7bb71"
  },
  "ISFP_F": {
    "hair": "#dca520",
    "skin": "#bf9e6d",
    "top": "#ab8f5b",
    "bottom": "#b89551",
    "accent": "#fdc320"
  },
  "ISFP_M": {
    "hair": "#e6af1e",
    "skin": "#b89e6e",
    "top": "#c79439",
    "bottom": "#af8440",
    "accent": "#fabb1a"
  },
  "ISTJ_F": {
    "hair": "#607d7c",
    "skin": "#f6d7ad",
    "top": "#538882",
    "bottom": "#417779",
    "accent": "#e0b367"
  },
  "ISTJ_M": {
    "hair": "#aea9a2",
    "skin": "#f1d0a3",
    "top": "#658a83",
    "bottom": "#597f78",
    "accent": "#e3a46c"
  },
  "ISTP_F": {
    "hair": "#95713a",
    "skin": "#d1b383",
    "top": "#a08342",
    "bottom": "#8a6d3c",
    "accent": "#f8bb0d"
  },
  "ISTP_M": {
    "hair": "#b18727",
    "skin": "#efcf97",
    "top": "#947d41",
    "bottom": "#a27a2e",
    "accent": "#f4b517"
  }
};

export function getPalette(id) {
  return PALETTES[id];
}
